//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.SunSetAndSunRiseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET/", ConfigurationName="SunSetAndSunRiseService.SunSetRiseServiceSoap")]
    public interface SunSetRiseServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetSunSetRiseTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.SunSetAndSunRiseService.LatLonDate GetSunSetRiseTime(Client.SunSetAndSunRiseService.LatLonDate L);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetSunSetRiseTime", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.SunSetAndSunRiseService.LatLonDate> GetSunSetRiseTimeAsync(Client.SunSetAndSunRiseService.LatLonDate L);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET/")]
    public partial class LatLonDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float latitudeField;
        
        private float longitudeField;
        
        private float sunSetTimeField;
        
        private float sunRiseTimeField;
        
        private int timeZoneField;
        
        private int dayField;
        
        private int monthField;
        
        private int yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float SunSetTime {
            get {
                return this.sunSetTimeField;
            }
            set {
                this.sunSetTimeField = value;
                this.RaisePropertyChanged("SunSetTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float SunRiseTime {
            get {
                return this.sunRiseTimeField;
            }
            set {
                this.sunRiseTimeField = value;
                this.RaisePropertyChanged("SunRiseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
                this.RaisePropertyChanged("TimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("Day");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SunSetRiseServiceSoapChannel : Client.SunSetAndSunRiseService.SunSetRiseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SunSetRiseServiceSoapClient : System.ServiceModel.ClientBase<Client.SunSetAndSunRiseService.SunSetRiseServiceSoap>, Client.SunSetAndSunRiseService.SunSetRiseServiceSoap {
        
        public SunSetRiseServiceSoapClient() {
        }
        
        public SunSetRiseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SunSetRiseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SunSetRiseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SunSetRiseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.SunSetAndSunRiseService.LatLonDate GetSunSetRiseTime(Client.SunSetAndSunRiseService.LatLonDate L) {
            return base.Channel.GetSunSetRiseTime(L);
        }
        
        public System.Threading.Tasks.Task<Client.SunSetAndSunRiseService.LatLonDate> GetSunSetRiseTimeAsync(Client.SunSetAndSunRiseService.LatLonDate L) {
            return base.Channel.GetSunSetRiseTimeAsync(L);
        }
    }
}
